language: go
sudo: false

go:
  - 1.7

cache:
  directories:
    - vendor

services:
  - memcached
  - redis

before_install:
  - go get -v github.com/bradfitz/gomemcache/memcache

install:
  - make dependencies
  #- make setup-ci

script:
  - make lint
  - make test

after_success:
  - make coveralls