language: go

go:
  - 1.7

services:
  - memcached
  - redis

before_install:
  - go get -v github.com/bradfitz/gomemcache/memcache

install:
  - make setup-ci


script:
  - go test -v ./..
  - make test-race
