sudo: false
language: go

go:
  - 1.7

cache:
  directories:
    - vendor

services:
  - memcached
  - redis

install:
  - make setup-ci

script:
  - make lint
  - make test

after_success:
  - make coveralls