sudo: false
language: go

go:
  - 1.7

services:
  - memcached
  - redis

before_install:
  - go get -v github.com/bradfitz/gomemcache/memcache

install:
  - make setup-ci

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go tool vet .
  - make test-race
